name: build

on:
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run phpcs
        run: ./vendor/bin/phpcs

      - name: Run phpunit
        run: ./vendor/bin/phpunit
